language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
# script:
# - CI=false npm run build
# deploy:
#   provider: heroku
#   app:
#     master: theresa-on-the-town
#     staging: theresa-staging
  